from fastapi import APIRouter

from app.api.v1.endpoints import admin, auth, cards, chat, config, discover, explore, face_scan_ws, gift_cards, linkedin, location, lookup, marketing, mini_games, moderation, pickup_lines, profile, score, subscription, university, upload, users, verification_ws

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(config.router)
api_router.include_router(auth.router)
api_router.include_router(profile.router)
api_router.include_router(users.router)
api_router.include_router(lookup.router)
api_router.include_router(upload.router)
api_router.include_router(subscription.router)
api_router.include_router(gift_cards.router)
api_router.include_router(location.router)
api_router.include_router(admin.router)
api_router.include_router(marketing.router)
api_router.include_router(verification_ws.router)
api_router.include_router(face_scan_ws.router)
api_router.include_router(linkedin.router)
api_router.include_router(explore.router)
api_router.include_router(discover.router)
api_router.include_router(chat.router)
api_router.include_router(chat.ws_router)
api_router.include_router(score.router)
api_router.include_router(cards.cards_router)
api_router.include_router(mini_games.mini_games_router)
api_router.include_router(pickup_lines.pickup_lines_router)
api_router.include_router(university.router)
api_router.include_router(moderation.router)